---
- hosts: localhost
  become: true
  vars:
    apps_common:
      - htop
      - emacs
      - vim
      - axel
      - maven
      - gradle
      
    apps_debian:
      - openjdk-11-jdk
      
    apps_archlinux:
      - jdk-openjdk

  tasks:
      # add-apt-repository depends on software-prpoerties-common
      - name: "debian install software-properties-common and update cache"
      apt:
        name: 'software-properties-common'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "prepare for install jdk"
      shell: add-apt-repository ppa:webupd8team/java -y
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "install apps for debian"
      apt:
        name: '{{ apps_common }} + {{ apps_debian }}'
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "install apps for archlinux"
      pacman:
        name: '{{ apps_common }} + {{ apps_archlinux }}'
        state: latest
      when: ansible_distribution == 'Archlinux'

    - name: config /etc/profile
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
      with_items:
        - "alias ll = 'ls -l --color=auto'"
        - "alias la = 'ls -la --color=auto'"      

