- hosts: localhost
  become: true
  vars:
    app_list:
      - htop
      - emacs
      - vim

  tasks:
    - name: debug
      debug:
        msg: "dist {{ ansible_distribution }}"

    - name: "Install apps"
      apt:
        name: '{{ app_list }}'
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "Install apps"
      pacman:
        name: '{{ app_list }}'
      when: ansible_distribution == 'Archlinux'

    - name: config /etc/profile
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
      with_items:
        - "alias ll = 'ls -l --color=auto'"
        - "alias la = 'ls -la --color=auto'"      
