---
- hosts: localhost
  become: true
  vars:
    apps_common:
      - htop
      - emacs
      - vim
      - axel
      - maven
      - gradle
      
    apps_debian:
      - emacs

    apps_archlinux:
      - jdk-openjdk

  tasks:
    - name: create user
      user:
        name: wiloon
        password: '$6$bNo6nGRA$DM/VghgjxTongwZm4BUL7jkw4lfF1nETHxk/YqVmbIGDO3HEzXXrTWeCw1WF7ZLkfgmt2w/Ta02xn2jbQdJNi/'
        shell: /bin/bash

    - name: chown /home/wiloon
      file:
        path: "/home/wiloon"
        owner: wiloon
        group: wiloon
        mode: '0755'
