---
- hosts: localhost
  become: true
  vars:
    apps_common:
      - htop
      - emacs
      - aria2
      - maven
      
    apps_debian:
      - emacs
      - ldnsutils
      - vimi
      - openjdk-11-jdk
      - openjdk-8-jdk
      
    apps_archlinux:
      - jdk-openjdk
      - svn
      - git
      - gradle
      - gvim

  tasks:
    - name: Display all variables/facts known for a host
      debug:
        msg: "archlinux init"

    - name: create user
      user:
        name: wiloon
        password: '$6$bNo6nGRA$DM/VghgjxTongwZm4BUL7jkw4lfF1nETHxk/YqVmbIGDO3HEzXXrTWeCw1WF7ZLkfgmt2w/Ta02xn2jbQdJNi/'
        shell: /bin/bash

    - name: chown /home/wiloon
      file:
        path: "/home/wiloon"
        owner: wiloon
        group: wiloon
        mode: '0755'

    - name: config /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ item }}"
      with_items:
        - "wiloon ALL=(ALL) NOPASSWD: ALL"

    - name: "debian install emacs and update cache"
      apt:
        name: 'emacs'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - slow_task

    - name: "install apps for debian"
      apt:
        name: '{{ apps_common }} + {{ apps_debian }}'
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "install apps for archlinux"
      pacman:
        name: '{{ apps_common }} + {{ apps_archlinux }}'
        state: latest
      when: ansible_distribution == 'Archlinux'

    - name: config /etc/profile
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
      with_items:
        - "alias ll='ls -l --color=auto'"
        - "alias la='ls -la --color=auto'"
        - "export JAVA_HOME=/usr/local/bin/jdk-12"
        - "export PATH=$JAVA_HOME/bin:$PATH"

    - name: mk /home/wiloon/.ssh
      file:
        path: /home/wiloon/.ssh
        state: directory

    - name: config .ssh/config
      blockinfile:
        path: /home/wiloon/.ssh/config
        create: yes
        owner: wiloon
        group: wiloon
        block: |
          host aliyun
            hostname wiloon.com
            user wiloon
            port 1022

          host nuc
            hostname nuc
            user root
            port 22

          host cstick
            hostname 192.168.50.215
            user wiloon
            port 22
    - name: mk /home/wiloon/.ssh/id_rsa
      file:
        path: /home/wiloon/.ssh/id_rsa
        state: touch
        owner: wiloon
        group: wiloon

    - name: enable sshd
      systemd:
        name: sshd
        state: started
        enabled: yes
