---
- hosts: localhost
  become: true
  vars:
    apps_common:
      - htop
      - emacs
      - git

    apps_debian:
      - emacs
      - ldnsutils
      - vim
      - default-jdk
      - git-svn
      - gnome-keyring
      - jq
      
    apps_archlinux:
      - gvim
      - wqy-microhei
      - sudo

    apps_archlinux_dev:
      - jdk-openjdk
      - svn
      - gradle
      - code
      - perl-term-readkey
      - maven
      - aria2

  tasks:
    - name: Display all variables/facts known for a host
      debug:
        msg: "archlinux init"

    - name: create user
      user:
        name: wiloon
        password: '$6$bNo6nGRA$DM/VghgjxTongwZm4BUL7jkw4lfF1nETHxk/YqVmbIGDO3HEzXXrTWeCw1WF7ZLkfgmt2w/Ta02xn2jbQdJNi/'
        shell: /bin/bash

    - name: chown /home/wiloon
      file:
        path: "/home/wiloon"
        owner: wiloon
        group: wiloon
        mode: '0755'

    - name: config /etc/sudoers
      lineinfile:
        path: /etc/sudoers
        line: "{{ item }}"
      with_items:
        - "wiloon ALL=(ALL) NOPASSWD: ALL"

    - name: "debian install emacs and update cache"
      apt:
        name: 'emacs'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - slow_task

    - name: "install apps for debian"
      apt:
        name: '{{ apps_common }} + {{ apps_debian }}'
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "install apps for archlinux"
      pacman:
        name: '{{ apps_common }} + {{ apps_archlinux }}'
        state: latest
      when: ansible_distribution == 'Archlinux'

    - name: "install apps for archlinux"
      pacman:
        name: '{{ apps_archlinux_dev }}'
        state: latest
      when: ansible_distribution == 'Archlinux'
      tags:
        - dev

    - name: mk /home/{{user_name}}/.ssh
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{user_name}}"
        group: "{{user_name}}"
      with_items:
        - "/home/{{user_name}}/.ssh"
        - "/home/{{user_name}}/bin"
        - "/home/{{user_name}}/apps"
        - "/home/{{user_name}}/apps/gopath"
        - "/data"

    - name: config shell
      lineinfile:
        path: /home/{{user_name}}/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias ll='ls -l --color=auto'"
        - "alias la='ls -la --color=auto'"
        - "export JAVA_HOME=/usr/lib/jvm/default-runtime"
        - "export GOROOT=/home/{{user_name}}/apps/go"
        - "export GOPATH=/home/{{user_name}}/apps/gopath"
        - "export GOPROXY=https://goproxy.cn"
        - "export PATH=$GOROOT/bin:$GOPATH/bin:/home/{{user_name}}/bin:$JAVA_HOME/bin:$PATH"

    - name: config .ssh/config
      blockinfile:
        path: /home/{{user_name}}/.ssh/config
        create: yes
        owner: "{{user_name}}"
        group: "{{user_name}}"
        block: |
          host aliyun
            hostname wiloon.com
            user wiloon
            port 1022
          host router
            hostname router
            user root
            port 99
          host dell
            hostname dell
            user root
            port 22

    - name: mk /home/{{user_name}}/.ssh/id_rsa
      file:
        path: /home/{{user_name}}/.ssh/id_rsa
        state: touch
        owner: "{{user_name}}"
        group: "{{user_name}}"

    - name: enable sshd
      systemd:
        name: sshd
        state: started
        enabled: yes

    - name: print jdk version
      ansible.builtin.shell: java -version
      tags:
        - dev