- hosts: localhost
  become: true
  vars:
    app_list:
      - - htop
        - emacs
        - vim
  tasks:
    - name: "Install apps"
      apt:
        name: "{{ item }}"
        state: present 
      with_items: "{{ app_list }}"

    - name: config /etc/profile
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
      with_items:
        - "alias ll = 'ls -l --color=auto'"
        - "alias la = 'ls -la --color=auto'"      
